apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-backend
  labels:
    app: backend
spec:
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: hello-backend
        image: jbugman/hello-kube-backend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: backend